# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9fd275d862c675142a61cf6f07aff2dc"
name = "Draft Order App"
handle = "draft-orders-app-4"
application_url = "https://title-failure-bufing-portrait.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes,write_draft_orders"

[auth]
redirect_urls = ["https://title-failure-bufing-portrait.trycloudflare.com/auth/callback", "https://title-failure-bufing-portrait.trycloudflare.com/auth/shopify/callback", "https://title-failure-bufing-portrait.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
