# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9fd275d862c675142a61cf6f07aff2dc"
name = "Draft Order App"
handle = "draft-orders-app-4"
application_url = "https://brokers-subscribe-rec-aims.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,read_draft_orders,write_products,read_products,read_customers,write_draft_orders,write_customers"

[auth]
redirect_urls = ["https://brokers-subscribe-rec-aims.trycloudflare.com/auth/callback", "https://brokers-subscribe-rec-aims.trycloudflare.com/auth/shopify/callback", "https://brokers-subscribe-rec-aims.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
